<?php


namespace Kckj\Mgo\Type;


use Doctrine\ODM\MongoDB\Types\ClosureToPHP;
use Doctrine\ODM\MongoDB\Types\Type;
use InvalidArgumentException;

class StringArray extends Type
{
    protected $type = 'string_array';

    use ClosureToPHP;

    public function convertToPHPValue($value): ?array
    {
        return parent::convertToPHPValue($value); // TODO: Change the autogenerated stub
    }

    public function convertToDatabaseValue($value): array
    {
        if (!is_array($value)) {
            throw new InvalidArgumentException(sprintf('Invalid type specified "%s".', $this->type));
        }
        foreach ($value as $val) {
            if (!is_string($val)) {
                throw new InvalidArgumentException(sprintf('Invalid type specified "%s".', $this->type));
            }
        }
        return parent::convertToDatabaseValue($value); // TODO: Change the autogenerated stub
    }
}